Algoritmo "crescente"



Var

   x, y : real

Inicio

   escreval("Digite dois numeros: ")
   leia(x)
   leia(y)


   enquanto x > y faca
      escreval("DESCRESCENTE!")
      escreval("Digite outros dois numeros: ")
      leia(x)
      leia(y)
   fimenquanto

   enquanto x < y faca
      escreval("CRESCENTE!")
      escreval("Digite outros dois numeros: ")
      leia(x)
      leia(y)
   fimenquanto


Fimalgoritmo